apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault-consul
  labels:
    app: vault
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: vault
  selector:
    app: vault